In [1]:
import pandas as pd
import numpy as np
from dateutil.parser import parse

In [2]:
# Read in file 
df = pd.read_csv('amazon_dataBooks.csv')
df.head()

,title,name,sellingPrice,listingPrice,typeOfBook,printLength,publicationDate,rating,reviews,availability
0,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalter \n(Author),£10.11,RRP: £10.99,Paperback – 13 Feb. 2020,Print length 448 pages,Publication date 13 Feb. 2020,4.5 out of 5 stars,"3,615 ratings",In stock
1,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Junior \n(Author),£6.85,NaN,"Paperback – Large Print, 30 July 2022",Print length 72 pages,Publication date 30 July 2022,4.5 out of 5 stars,2 ratings,In stock
2,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic \n(Author),£23.49,RRP: £32.95,Paperback – 20 Nov. 2015,Print length 288 pages,Publication date 20 Nov. 2015,4.6 out of 5 stars,"4,651 ratings",In stock
3,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald \n(Author),£11.79,NaN,Paperback – 21 July 2019,Print length 159 pages,Publication date 21 July 2019,4.3 out of 5 stars,464 ratings,In stock
4,"Becoming a Data Head: How to Think, Speak, and...","Alex J. Gutman \n(Author),",£23.09,RRP: £33.00,Paperback – 24 Jun. 2021,Print length 272 pages,Publication date 24 Jun. 2021,4.6 out of 5 stars,310 ratings,In stock

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            310 non-null    object
 1   name             300 non-null    object
 2   sellingPrice     239 non-null    object
 3   listingPrice     127 non-null    object
 4   typeOfBook       301 non-null    object
 5   printLength      233 non-null    object
 6   publicationDate  300 non-null    object
 7   rating           310 non-null    object
 8   reviews          260 non-null    object
 9   availability     309 non-null    object
dtypes: object(10)
memory usage: 24.3+ KB

In [4]:
# Reset index to start at 1
df.index +=1 # Increasing each index value by 1
df.head()

,title,name,sellingPrice,listingPrice,typeOfBook,printLength,publicationDate,rating,reviews,availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalter \n(Author),£10.11,RRP: £10.99,Paperback – 13 Feb. 2020,Print length 448 pages,Publication date 13 Feb. 2020,4.5 out of 5 stars,"3,615 ratings",In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Junior \n(Author),£6.85,NaN,"Paperback – Large Print, 30 July 2022",Print length 72 pages,Publication date 30 July 2022,4.5 out of 5 stars,2 ratings,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic \n(Author),£23.49,RRP: £32.95,Paperback – 20 Nov. 2015,Print length 288 pages,Publication date 20 Nov. 2015,4.6 out of 5 stars,"4,651 ratings",In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald \n(Author),£11.79,NaN,Paperback – 21 July 2019,Print length 159 pages,Publication date 21 July 2019,4.3 out of 5 stars,464 ratings,In stock
5,"Becoming a Data Head: How to Think, Speak, and...","Alex J. Gutman \n(Author),",£23.09,RRP: £33.00,Paperback – 24 Jun. 2021,Print length 272 pages,Publication date 24 Jun. 2021,4.6 out of 5 stars,310 ratings,In stock

### Renaming headers

In [5]:
df_new = df.rename(columns={'title': 'BookTitle', 
                            'name': 'AuthorName',
                            'sellingPrice': 'SellingPrice',
                            'listingPrice': 'ListingPrice',
                            'typeOfBook': 'TypeofBook',
                            'printLength': 'PrintLength',
                            'publicationDate': 'PublicationDate',
                            'rating': 'Rating',
                            'reviews': 'ReviewCount',
                            'availability': 'Availability'
                           })
df_new.head()

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalter \n(Author),£10.11,RRP: £10.99,Paperback – 13 Feb. 2020,Print length 448 pages,Publication date 13 Feb. 2020,4.5 out of 5 stars,"3,615 ratings",In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Junior \n(Author),£6.85,NaN,"Paperback – Large Print, 30 July 2022",Print length 72 pages,Publication date 30 July 2022,4.5 out of 5 stars,2 ratings,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic \n(Author),£23.49,RRP: £32.95,Paperback – 20 Nov. 2015,Print length 288 pages,Publication date 20 Nov. 2015,4.6 out of 5 stars,"4,651 ratings",In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald \n(Author),£11.79,NaN,Paperback – 21 July 2019,Print length 159 pages,Publication date 21 July 2019,4.3 out of 5 stars,464 ratings,In stock
5,"Becoming a Data Head: How to Think, Speak, and...","Alex J. Gutman \n(Author),",£23.09,RRP: £33.00,Paperback – 24 Jun. 2021,Print length 272 pages,Publication date 24 Jun. 2021,4.6 out of 5 stars,310 ratings,In stock

### Cleaning Attribute values

In [6]:
# Cleaning the AuthorName column by removing " \n(Author)"
df_new['AuthorName'] = df_new['AuthorName'].str.rstrip(' \n(Author),')

# Cleaning SellingPrice column by removing leading "£"
df_new['SellingPrice'] = df_new['SellingPrice'].str.strip('£')

# Cleaning ListingPrice column by removing leading "RRP: £ & Was: £"
df_new['ListingPrice'] = df_new['ListingPrice'].str.strip('RRP: £, Was: £')

# Cleaning PrintLength column by removing "Print length, pages" txt
df_new['PrintLength'] = df_new['PrintLength'].str.strip('Print length, pages')

# Cleaning ReviewCount column by removing the text "ratings" & commas
df_new['ReviewCount'] = df_new['ReviewCount'].str.strip('ratings')
df_new['ReviewCount'] = df_new['ReviewCount'].str.replace(',','')

# Cleaning PublicationDate column by removing leading "Publication date: " txt
df_new['PublicationDate'] = df_new['PublicationDate'].str.strip('Publication date')

# Removing the date and hyphen, keeping only the book type
df_new['TypeofBook'] = df_new['TypeofBook'].str.split('–').str[0].str.strip()

# Removing the "out of 5 stars" text from Rating column
df_new['Rating'] = df_new['Rating'].str.split('out').str[0].str.strip()

df_new

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13 Feb. 2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,NaN,Paperback,72,30 July 2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20 Nov. 2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,NaN,Paperback,159,21 July 2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24 Jun. 2021,4.6,310,In stock
...,...,...,...,...,...,...,...,...,...,...
306,Tinpot: Football's Forgotten Tournaments… from...,Simon Turne,11.99,14.99,Paperback,320,5 Aug. 2024,Previous slide of product details,NaN,"This title will be released on August 5, 2024...."
307,"Queer Data: Using Gender, Sex and Sexuality Da...",Kevin Guyan,16.79,19.99,Paperback,240,13 Jan. 2022,5.0,11,Only 3 left in stock (more on the way).
308,"Fish Mouth Sewing Machine Needle Threader, 202...",NaN,8.99,NaN,NaN,NaN,NaN,Previous page of related Sponsored Products,NaN,Usually dispatched within 2 to 3 days
309,Data Engineering with Python: Work with massiv...,Paul Crickard,38.84,NaN,Paperback,356,10 Nov. 2020,4.1,125,In stock
310,Data Teams: A Unified Management Model for Suc...,Jesse Anderson,NaN,NaN,"1st ed. Edition, Kindle Edition",NaN,18 Sept. 2020,4.3,49,Out of stock

### Replacing NaN values

In [7]:
# cehcking total NaN values for each column 
null_counts = df_new.isnull().sum()
print("\nNull counts:")
print(null_counts)

Null counts:
BookTitle            0
AuthorName          10
SellingPrice        71
ListingPrice       183
TypeofBook           9
PrintLength         77
PublicationDate     10
Rating               0
ReviewCount         50
Availability         1
dtype: int64

In [8]:
# Fill NaN values for each column based on the dict values
fill_values = {
    'AuthorName': 'Unknown',
    'SellingPrice': 0,
    'ListingPrice': 0,
    'TypeofBook': 'Unknown',
    'PrintLength': 0,
    'PublicationDate': 0,
    'ReviewCount': 0,
    'Availability': 'Unknown'
}

df_new.fillna(value=fill_values, inplace=True)

In [9]:
# cehcking total NaN values for each column 
null_counts = df_new.isnull().sum()
print("\nNull counts:")
print(null_counts)

Null counts:
BookTitle          0
AuthorName         0
SellingPrice       0
ListingPrice       0
TypeofBook         0
PrintLength        0
PublicationDate    0
Rating             0
ReviewCount        0
Availability       0
dtype: int64

### Changing dataTypes of each attribute

In [10]:
# Checking current dtypes for each attribute
print(df_new.dtypes)

BookTitle          object
AuthorName         object
SellingPrice       object
ListingPrice       object
TypeofBook         object
PrintLength        object
PublicationDate    object
Rating             object
ReviewCount        object
Availability       object
dtype: object

In [11]:
data_types = {
    'SellingPrice': float,
    'ListingPrice': float,
    'PrintLength': int,
    'ReviewCount': int
}
# Converting data types for specified columns
df_new = df_new.astype(data_types)

df_new

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13 Feb. 2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,0.00,Paperback,72,30 July 2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20 Nov. 2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,0.00,Paperback,159,21 July 2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24 Jun. 2021,4.6,310,In stock
...,...,...,...,...,...,...,...,...,...,...
306,Tinpot: Football's Forgotten Tournaments… from...,Simon Turne,11.99,14.99,Paperback,320,5 Aug. 2024,Previous slide of product details,0,"This title will be released on August 5, 2024...."
307,"Queer Data: Using Gender, Sex and Sexuality Da...",Kevin Guyan,16.79,19.99,Paperback,240,13 Jan. 2022,5.0,11,Only 3 left in stock (more on the way).
308,"Fish Mouth Sewing Machine Needle Threader, 202...",Unknown,8.99,0.00,Unknown,0,0,Previous page of related Sponsored Products,0,Usually dispatched within 2 to 3 days
309,Data Engineering with Python: Work with massiv...,Paul Crickard,38.84,0.00,Paperback,356,10 Nov. 2020,4.1,125,In stock
310,Data Teams: A Unified Management Model for Suc...,Jesse Anderson,0.00,0.00,"1st ed. Edition, Kindle Edition",0,18 Sept. 2020,4.3,49,Out of stock

In [12]:
#Defining a function to parse and format dates in the publicationDate column 
def parse_and_format_date(date):
    if isinstance(date, str):
        try:
            parsed_date = parse(date)
            return parsed_date.strftime('%d/%m/%Y')
        except ValueError:
            return date #returns the original val if parsing fails 
    return date

#Applying the function to the publicationDate column
df_new['PublicationDate'] = df_new['PublicationDate'].apply(parse_and_format_date)
df_new

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13/02/2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,0.00,Paperback,72,30/07/2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20/11/2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,0.00,Paperback,159,21/07/2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24/06/2021,4.6,310,In stock
...,...,...,...,...,...,...,...,...,...,...
306,Tinpot: Football's Forgotten Tournaments… from...,Simon Turne,11.99,14.99,Paperback,320,05/08/2024,Previous slide of product details,0,"This title will be released on August 5, 2024...."
307,"Queer Data: Using Gender, Sex and Sexuality Da...",Kevin Guyan,16.79,19.99,Paperback,240,13/01/2022,5.0,11,Only 3 left in stock (more on the way).
308,"Fish Mouth Sewing Machine Needle Threader, 202...",Unknown,8.99,0.00,Unknown,0,0,Previous page of related Sponsored Products,0,Usually dispatched within 2 to 3 days
309,Data Engineering with Python: Work with massiv...,Paul Crickard,38.84,0.00,Paperback,356,10/11/2020,4.1,125,In stock
310,Data Teams: A Unified Management Model for Suc...,Jesse Anderson,0.00,0.00,"1st ed. Edition, Kindle Edition",0,18/09/2020,4.3,49,Out of stock

In [13]:
# Converting non-numeric values in Rating column to NaN 
def to_float(value):
    try:
        return float(value)
    except ValueError:
        return np.nan
    
# Applying the function to the 'Rating' column
df_new['Rating'] = df_new['Rating'].apply(to_float)
# Fill NaN values with 0
df_new['Rating'] = df_new['Rating'].fillna(0)
# Concerting Rating column to float dtype
df_new['Rating'] = df_new['Rating'].astype(float)

In [14]:
# Filtering rows with availability indicating stock levels
# stock_pattern = r'only \d+ left in stock.*'
# filtered_df = df_new[df_new['Availability'].str.contains(stock_pattern, case=False, regex=True)]

# filtered_df

In [15]:
# Replacing entries indicating stock levels or dispatch time with "In Stock"
patterns = r'only \d+ left in stock.*|Usually dispatched within \d+ to \d+ (days|months)'
df_new['Availability'] = df_new['Availability'].str.replace(patterns, 'In Stock', case=False, regex=True)
df_new

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13/02/2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,0.00,Paperback,72,30/07/2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20/11/2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,0.00,Paperback,159,21/07/2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24/06/2021,4.6,310,In stock
...,...,...,...,...,...,...,...,...,...,...
306,Tinpot: Football's Forgotten Tournaments… from...,Simon Turne,11.99,14.99,Paperback,320,05/08/2024,0.0,0,"This title will be released on August 5, 2024...."
307,"Queer Data: Using Gender, Sex and Sexuality Da...",Kevin Guyan,16.79,19.99,Paperback,240,13/01/2022,5.0,11,In Stock
308,"Fish Mouth Sewing Machine Needle Threader, 202...",Unknown,8.99,0.00,Unknown,0,0,0.0,0,In Stock
309,Data Engineering with Python: Work with massiv...,Paul Crickard,38.84,0.00,Paperback,356,10/11/2020,4.1,125,In stock
310,Data Teams: A Unified Management Model for Suc...,Jesse Anderson,0.00,0.00,"1st ed. Edition, Kindle Edition",0,18/09/2020,4.3,49,Out of stock

In [16]:
# View changed dtypes for each attribute
print(df_new.dtypes)

BookTitle           object
AuthorName          object
SellingPrice       float64
ListingPrice       float64
TypeofBook          object
PrintLength          int32
PublicationDate     object
Rating             float64
ReviewCount          int32
Availability        object
dtype: object

In [17]:
df_new.iloc[:10]

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13/02/2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,0.00,Paperback,72,30/07/2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20/11/2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,0.00,Paperback,159,21/07/2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24/06/2021,4.6,310,In stock
6,How to Win the Premier League: The Inside Stor...,Ian Graham,16.99,22.00,Hardcover,320,15/08/2024,0.0,0,"This title will be released on August 15, 2024..."
7,Microsoft Power BI Data Analyst Certification ...,Orrin Edenfield,33.99,0.00,Paperback,398,24/06/2022,4.0,44,In stock
8,AI & Data Literacy: Empowering Citizens of Dat...,Bill Schmarz,22.99,0.00,Paperback,202,09/08/2023,4.6,33,In stock
9,Data Grab: The new Colonialism of Big Tech and...,Ulises A. Mejias,15.16,22.00,Hardcover,320,08/02/2024,4.7,8,In stock
10,Engineers′ Data Book,Clifford Matthews,16.25,0.00,Paperback,344,27/01/2012,4.6,176,In stock

 ### Checking for duplicates

In [18]:
# Checking for total rows before removing duplicates
total_rows = df_new.shape[0]
print("Total rows in the original DataFrame: ", total_rows)

Total rows in the original DataFrame:  310

In [19]:
# Finding duplicate rows based on 4 attributes & sorting bsed on BookTitle 

duplicated = df_new[df_new.duplicated(['BookTitle','AuthorName','PrintLength', 'PublicationDate'], keep=False)].sort_values('BookTitle')

duplicated.iloc[:15]

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
124,A Common–Sense Guide to Data Structures and Al...,Jan Wengrow,23.44,36.99,Paperback,250,30/06/2020,4.8,733,In stock
139,A Common–Sense Guide to Data Structures and Al...,Jan Wengrow,23.44,36.99,Paperback,250,30/06/2020,4.8,733,In stock
147,A Common–Sense Guide to Data Structures and Al...,Jan Wengrow,23.44,36.99,Paperback,250,30/06/2020,4.8,733,In stock
279,A Handbook for Data Analysis in the Behavioria...,Gideon Keren \n(Edi,88.02,96.99,Paperback,586,01/11/1992,0.0,0,In Stock
248,A Handbook for Data Analysis in the Behavioria...,Gideon Keren \n(Edi,88.02,96.99,Paperback,586,01/11/1992,0.0,0,In Stock
76,A Little Guide for Teachers: Using Student Data,Richard Selfridge,10.99,0.00,Paperback,88,26/06/2024,0.0,0,In stock
99,A Little Guide for Teachers: Using Student Data,Richard Selfridge,10.99,0.00,Paperback,88,26/06/2024,0.0,0,In stock
120,Azure Data Factory Cookbook: Build and manage ...,Dmitry Anoshin,37.99,0.00,Paperback,382,11/01/2021,4.0,41,In stock
136,Azure Data Factory Cookbook: Build and manage ...,Dmitry Anoshin,37.99,0.00,Paperback,382,11/01/2021,4.0,41,In stock
148,Azure Data Factory Cookbook: Build and manage ...,Dmitry Anoshin,37.99,0.00,Paperback,382,11/01/2021,4.0,41,In stock
282,"Big Data: Using SMART Big Data, Analytics and ...",Bernard Ma,11.75,15.00,Paperback,256,16/01/2015,4.1,275,In stock
260,"Big Data: Using SMART Big Data, Analytics and ...",Bernard Ma,11.75,15.00,Paperback,256,16/01/2015,4.1,275,In stock
216,"Big Data: Using SMART Big Data, Analytics and ...",Bernard Ma,11.75,15.00,Paperback,256,16/01/2015,4.1,275,In stock
142,Building Data Science Applications with FastAP...,François Voron,0.00,0.00,Kindle Edition,0,31/07/2023,5.0,4,Out of stock
145,Building Data Science Applications with FastAP...,François Voron,0.00,0.00,Kindle Edition,0,31/07/2023,5.0,4,Out of stock

In [20]:
# Count the number of duplicated rows
dup_count = duplicated.shape[0]
print("Number of duplicated rows: ", dup_count)

Number of duplicated rows:  130

In [21]:
# Save the DataFrame with duplicated rows to a CSV file
# duplicated.to_csv('duplicated_rows.csv', index=False)

In [22]:
# Dropping duplicates from the original df
df_no_duplicates = df_new.drop_duplicates(['BookTitle', 'AuthorName', 'PrintLength', 'PublicationDate'])

# Counting remaining rows after dropping duplicates
remaining_rows = df_no_duplicates.shape[0]
print("Number of rows after dropping duplicates: ", remaining_rows)

Number of rows after dropping duplicates:  235

In [23]:
# Calculating the num of rows removed 
rows_removed = total_rows - remaining_rows 
print("Number of rows removed: ", rows_removed)

Number of rows removed:  75

In [24]:
df_no_duplicates[:188]

,BookTitle,AuthorName,SellingPrice,ListingPrice,TypeofBook,PrintLength,PublicationDate,Rating,ReviewCount,Availability
1,The Art of Statistics: Learning from Data (Pel...,David Spiegelhalte,10.11,10.99,Paperback,448,13/02/2020,4.5,3615,In stock
2,"Data Scientist Coloring Book. A Funny, Unique,...",Witty Jobs Juni,6.85,0.00,Paperback,72,30/07/2022,4.5,2,In stock
3,Storytelling with Data: A Data Visualization G...,Cole Nussbaumer Knaflic,23.49,32.95,Paperback,288,20/11/2015,4.6,4651,In stock
4,Data Analytics for Absolute Beginners: A Decon...,Oliver Theobald,11.79,0.00,Paperback,159,21/07/2019,4.3,464,In stock
5,"Becoming a Data Head: How to Think, Speak, and...",Alex J. Gutman,23.09,33.00,Paperback,272,24/06/2021,4.6,310,In stock
...,...,...,...,...,...,...,...,...,...,...
229,Data Analytics with MS Excel & Power BI: This ...,Punit Prab,7.81,0.00,Paperback,177,06/04/2021,3.2,5,In stock
232,Qualitative Data Analysis - International Stud...,Matthew B. Miles,54.62,65.00,Paperback,408,22/01/2019,4.3,10,In stock
233,"Data Sketches: A journey of imagination, explo...",Nadieh Breme,37.05,39.99,Paperback,428,09/02/2021,4.5,103,In Stock
235,Murach's Python for Data Analysis (Training & ...,Scott McCoy,42.20,54.99,Paperback,235,01/08/2021,4.7,35,In stock
236,C# Data Structures and Algorithms: Harness the...,Marcin Jam,31.99,0.00,Paperback,372,29/02/2024,4.6,3,In stock

In [25]:
# Saving df to a csv file
df_no_duplicates.to_csv("cleaned-data.csv", header=True, index=False)